### PR TITLE
added unit test for the parseFraction util, modify to parseFraction t…

### PR DESCRIPTION
**Pull request by mdaxtman**
…o better handle edge cases

### CODE REVIEW

**Comment by tptee** [comment]
Here's the Travis linter output:
```
/home/travis/build/FormidableLabs/radium-grid/src/components/util/parse-fraction.js
  1:23  error  This function has too many statements (17). Maximum allowed is 15  max-statements
  6:5   error  Keyword "if" must be followed by whitespace                        space-after-keywords
  6:28  error  No magic number: -1                                                no-magic-numbers
  6:31  error  Missing space before opening brace                                 space-before-blocks
  9:64  error  There should be no spaces inside this paren                        space-in-parens
```

**Comment by tptee** [comment]
```
/home/travis/build/FormidableLabs/radium-grid/src/components/util/parse-fraction.js
  1:23  error  This function has too many statements (17). Maximum allowed is 15  max-statements
  6:29  error  No magic number: -1                                                no-magic-numbers
```

**Comment by tptee** [comment]
I wish eslint was smarter about indexOf re: `no-magic-numbers` :(

**Comment by mdaxtman** [comment]
spec is finally ready @tptee.

**Pull request merged**
